"""initial_schema

Revision ID: 0810afd0c1c2
Revises: 
Create Date: 2026-09-24 15:44:55.433876
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0810afd0c1c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING_VERIFICATION', name='farmer_status_enum'), nullable=False),
    sa.Column('registration_date', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_district'), 'farmers', ['district'], unique=False)
    op.create_index(op.f('ix_farmers_mobile_number'), 'farmers', ['mobile_number'], unique=False)
    op.create_index(op.f('ix_farmers_village'), 'farmers', ['village'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FIELD_OFFICER', 'FARMER', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='vendor_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'HARVESTED', name='field_status_enum'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('polygon_color', sa.Enum('GREEN', 'YELLOW', 'RED', 'BLUE', name='polygon_color_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_farmer_id'), 'fields', ['farmer_id'], unique=False)
    op.create_table('seed_supplies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=False),
    sa.Column('supply_date', sa.String(length=20), nullable=False),
    sa.Column('purchase_reference', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_supplies_vendor_id'), 'seed_supplies', ['vendor_id'], unique=False)
    op.create_table('seed_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supply_id', sa.String(length=36), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('received_quantity', sa.Float(), nullable=False),
    sa.Column('allocated_quantity', sa.Float(), nullable=False),
    sa.Column('available_quantity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allocated_quantity <= received_quantity', name='ck_allocated_lte_received'),
    sa.CheckConstraint('allocated_quantity >= 0', name='ck_allocated_qty_positive'),
    sa.CheckConstraint('available_quantity >= 0', name='ck_available_qty_non_negative'),
    sa.CheckConstraint('received_quantity >= 0', name='ck_received_qty_positive'),
    sa.ForeignKeyConstraint(['supply_id'], ['seed_supplies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_batches_batch_number'), 'seed_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_seed_batches_supply_id'), 'seed_batches', ['supply_id'], unique=False)
    op.create_table('seed_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seed_batch_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('allocation_date', sa.String(length=20), nullable=False),
    sa.Column('allocated_by', sa.String(length=36), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['allocated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seed_batch_id'], ['seed_batches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_allocations_farmer_id'), 'seed_allocations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_seed_allocations_field_id'), 'seed_allocations', ['field_id'], unique=False)
    op.create_index(op.f('ix_seed_allocations_seed_batch_id'), 'seed_allocations', ['seed_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seed_allocations_seed_batch_id'), table_name='seed_allocations')
    op.drop_index(op.f('ix_seed_allocations_field_id'), table_name='seed_allocations')
    op.drop_index(op.f('ix_seed_allocations_farmer_id'), table_name='seed_allocations')
    op.drop_table('seed_allocations')
    op.drop_index(op.f('ix_seed_batches_supply_id'), table_name='seed_batches')
    op.drop_index(op.f('ix_seed_batches_batch_number'), table_name='seed_batches')
    op.drop_table('seed_batches')
    op.drop_index(op.f('ix_seed_supplies_vendor_id'), table_name='seed_supplies')
    op.drop_table('seed_supplies')
    op.drop_index(op.f('ix_fields_farmer_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_farmers_village'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_mobile_number'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_district'), table_name='farmers')
    op.drop_table('farmers')
    # ### end Alembic commands ###
